version: 2
jobs:
  build:
    docker:
    - image: codesimple/elm:0.19
    steps:
    - checkout
    - run:
        name: Make elm
        command: elm make src/Main.elm --output static/main.js
    - persist_to_workspace:
        root: static
        paths:
            - .


  deploy:
    docker:
    - image: circleci/python:3.7
    # Update server image
    steps:
    - attach_workspace:
        at: static
    - run:
        name: LS
        command: ls -R
    - run:
        name: Install aws cli
        command: sudo pip install awscli
    - run:
        name: Deploy to S3
        command: aws s3 sync static s3://opencocktail --delete


  markdown_lint:
    docker:
    - image: 06kellyjac/markdownlint-cli:0.13.0-alpine
    steps:
    - checkout
    - run: markdownlint README.md

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - markdown_lint
    - build:
        filters:
          branches:
            only:
            - develop
            - master
    - deploy:
        requires:
        - build
