version: 2
jobs:
  build:
    docker:
    - image: codesimple/elm:0.19
    steps:
    - checkout
    - run:
        name: Make elm
        command: elm make src/Main.elm --output static/main.js
    - persist_to_workspace:
        root: static
        paths:
            - .


  markdown_lint:
    docker:
    - image: 06kellyjac/markdownlint-cli:0.13.0-alpine
    steps:
    - checkout
    - run: markdownlint README.md

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - markdown_lint
    - build:
        filters:
          branches:
            only:
            - develop
            - master
